name: Example Deploy to Amazon ECS

on:
  push:
    branches:
      - "prod"
    paths:
      - .github/workflows/example_deploy_ecs.yaml
      - "worker/**"

env:
  AWS_REGION: us-east-1                 
  ECR_REPOSITORY: voting-app 
  ECS_SERVICE_WORKER: worker-service          
  ECS_CLUSTER: demo-deploy
  WORKER_TASK_DEFINITION: worker/task-definition.json
  WORKER_CONTAINER_NAME: worker-container
  ENV: "prod"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Example Deploy Application to Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set Variable
      id: set-vars
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
      run: |
        echo "::set-output name=worker_image::$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG"

    - name: Fill in the new image ID in the Amazon ECS task definition (Worker)
      id: task-def-worker
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.WORKER_TASK_DEFINITION }}
        container-name: ${{ env.WORKER_CONTAINER_NAME }}
        image: ${{ steps.set-vars.outputs.worker_image }}

    - name: Deploy Amazon ECS task definition Worker
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_WORKER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
    
       